import type {OAuthProvider,OAuthSession} from './oauth';
interface HostReply {error?:string;value?:unknown;}
interface HostBridge {request(method:string,params?:Record<string,unknown>):Promise<HostReply>;}
function bridge(){return (globalThis as {__photonPlugin?:HostBridge}).__photonPlugin;}
const idFor=(provider:OAuthProvider)=>provider+'-session';
const originFor=(provider:OAuthProvider)=>provider==='codex'?'https://chatgpt.com':'https://api.x.ai';
export async function saveOAuthSession(provider:OAuthProvider,session:OAuthSession){const host=bridge();if(!host)return;const value=JSON.stringify({accessToken:session.accessToken,refreshToken:session.refreshToken,expiresAt:session.expiresAt,accountId:session.accountId,tokenEndpoint:session.tokenEndpoint});const reply=await host.request('sdk.credentials.store',{id:idFor(provider),origin:originFor(provider),value});if(reply?.error&&!/Unsupported Photon SDK capability/i.test(reply.error))throw new Error(reply.error);}
export async function loadOAuthSession(provider:OAuthProvider):Promise<OAuthSession|undefined>{const host=bridge();if(!host)return;const reply=await host.request('sdk.credentials.read',{id:idFor(provider)});if(reply?.error||typeof reply?.value!=='string'||!reply.value)return;try{const parsed=JSON.parse(reply.value);if(typeof parsed?.accessToken!=='string'||!parsed.accessToken)return;return {accessToken:parsed.accessToken,refreshToken:typeof parsed.refreshToken==='string'?parsed.refreshToken:undefined,expiresAt:Number.isFinite(Number(parsed.expiresAt))?Number(parsed.expiresAt):undefined,accountId:typeof parsed.accountId==='string'?parsed.accountId:undefined,tokenEndpoint:typeof parsed.tokenEndpoint==='string'?parsed.tokenEndpoint:undefined};}catch{return;}}
export async function clearOAuthSession(provider:OAuthProvider){const host=bridge();if(!host)return;await host.request('sdk.credentials.delete',{id:idFor(provider)});}
